### PR TITLE
368 turn off direct chat for spectators

### PR DESCRIPTION
**Pull request by NikkoJT**
See #368

### CODE REVIEW

**Review by SamLex — APPROVED** [review]
Looks good to me.

As an aside, I don't think this will work for slotted Spectators since I don't believe fn_activateSpectator is run for them. But this probably isn't an issue as these slots are rarely used.

**Comment by NikkoJT** [comment]
This fix currently persists into "real life" if the spectator reslots. I (or you) need to find a way to get around that before this can go ahead.

**Comment by SamLex** [comment]
I think the neatest, least impact way of doing this would be adding the `postInit` attribute to the [terminateSpectator](https://github.com/folkarps/F3/blob/c3b75cf083ba663c9c02b4eb88615e8fe2c80f65/f/functions.hpp#L114) function. I _think_ that'll execute it when a player JIPs.

It should be fine to run this in normal start and JIP scenarios; making sure `directChat` is enabled is whatever and terminating the spectator should be a no-op if it's not running. But this covers the JIP'ing spectator case as it re-enables `directChat` and makes sure the spectator is terminated (which we haven't seen issues with but you never know)

**Comment by NikkoJT** [comment]
That seems like a good avenue to explore but we need to make sure it accounts for people using the actual spectator slots.

**Comment by NikkoJT** [comment]
A fix for this was added in #360 - the radio system now turns on direct chat for non-spectator units as part of its initialisation

**Pull request merged**
