### PR TITLE
Issue 142: FTMemberMarkers fix JIP issues

### PR DESCRIPTION
**Pull request by shadow-fa**
Previously this component was drawing white markers for JIP players.
This was because `fn_LocalFTMarkerSync` was only "syncing" the values if they had changed from the group leaders perspective.
Additionally it would only sync if the group leader did not disconnect.

I'm not sure if this is the best solution to the problem, but I'm open to discuss any alternatives.

See also issue #142.

### CODE REVIEW

**Comment by SamLex** [comment]
Can't this component be significantly simplified now that `assignTeam` is global and with #163?

Quite a lot of the logic in this component (and what caused the JIP issue) is the syncing of the team colours using a variable on each unit, all of which is now redundant. So that logic could be removed and the markers just drawn based on the (now global) `assignedTeam`.

**Comment by shadow-fa** [comment]
It already is simplified because the syncing is gone.
What still has to be done is storing the colour in a variable for each unit, because at some points in the game (e.g. when the unit is controlling a UAV), we can't get the colour from the command because it would return `nil`. This would lead to the problem, that some units would sometimes have a different colour.

**Comment by SamLex** [comment]
Yeah, I should look more carefully before commenting.

Also, doesn't this run (unnecessarily) on the server (no `hasInterface` check)?

**Comment by shadow-fa** [comment]
It should run for every unit that has an interface, including the server if it isn't a dedicated server.

**Comment by SamLex** [comment]
Yes, but doesn't it currently run even on machines without an interface?

**Comment by shadow-fa** [comment]
You're right, I got it confused with another PR.
This (see last commit) is what you meant, right?

**Pull request merged**
