### PR TITLE
421 Gear updates alongside CDLC adoption

### PR DESCRIPTION
**Pull request by costno**
See issue #421

### CODE REVIEW

**Comment by Aqarius90** [comment]
* (3IFB) Galat with RPK? Seems... disparate.
* (3IFB) I see the theme with FIA, but would sooner vote for the SLR here.

**Comment by NikkoJT** [comment]
possibly 3IFB should have AKM as primary and Galat (75rd) as AR

**Comment by costno** [comment]
I went with mix of Galat and RPK to demonstrate the broad range of volunteers that have joined the Third. Might bias towards the Galat though.

> * (3IFB) I see the theme with FIA, but would sooner vote for the SLR here.

SLR for the Third or for FIA? I could see FIA with SLRs since SLR is likely an old standard service rifle for the AAF.

**Comment by Aqarius90** [comment]
SLR for DM for the Third. Hades is weird. It's a bolt action, but it's a visibly modern rifle. "Bespoke" is the word. As opposed to a "won this in a card game in Luanda" SLR.

**Review by NikkoJT — APPROVED** [review]
Looks OK to me

**Pull request merged**
